name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - main  # Executa o CI/CD quando houver um push na branch main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Verifica o repositório GitHub
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura o Docker para rodar o build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Configura o Docker para rodar no CI
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Referencia o segredo de usuário
          password: ${{ secrets.DOCKER_PASSWORD }}  # Referencia o segredo de senha

      # Build da imagem Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: earaujo/web-app001  # Substitua pelo seu Docker ID e repositório
